### ISSUE TITLE
When you play with double arrows weird things happen

### ISSUE THREAD

**Issue by sleepingchinchilla** [Tellmarch/playshogi#22] opened 2020-07-25 07:27 UTC
For example, at the end of the tsume you can still move your piece (plus it is your opponent move, so why would you be able to move anyway) - also making it wrong at the end

**Comment by ddugovic** [comment] 2020-08-05 23:46
Seems to be fixed?  At least I do not see how to reproduce it anymore.

**Comment by timezombi** [comment] 2020-08-06 05:24
@ddugovic  I'm still able to reproduce the issue, but not for most problems. Problem number [*715*](http://playshogi.com/#Tsume:715) on the production instance has this problem, however all the other random problems I tried seem to correctly identify that it is gote to move, however they would still highlight the squares of all of gote's moves when hovering over a piece. Not sure if that is still desired if the final position is checkmate.


Just in case the issue isn't clear, I'll restate the problem. When viewing a problem from its direct URL (I guess in "TsumeView" mode?), the ProblemFeedbackPanel has a GameNavigator visible. The GameNavigator allows you to step forwards and back through the defined solution. The problem that @sleepingchinchilla is reporting is this:

- First, note that you can interact with the pieces in this mode at any time, even when you have started iterating through the solution using the GameNavigator.

- Also note, if you use the GameNavigator to get to the end of the solution, it will probably be a checkmate in most situations. Even if it is _not_ a checkmate, it will still be *gote's* turn to move, not *sente's*! Therefore, it should be illegal to make a move as sente under these conditions.

- Finally, if you use the GameNavigator to proceed to the end of the solution line as before (sleepingchinchilla specifically mentions the lastButton / "Double Arrow" button), note that you can STILL interact with the pieces in hand or pieces on the board. This is despite the fact that the position is checkmate and/or gote's turn to play. Despite it being gote's turn to play, the game board still accepts moves from sente.

- When the position is the final position of the solution line, if you then move/drop any piece, the solution will be marked as wrong (even if the position is checkmate).

**Comment by ddugovic** [comment] 2020-08-06 10:31
Thanks, now I see it.  Problem number 715 data need to be sanitized to omit the (resign?) null move at the end, I imagine.

I am surprised that my patch (committed a minute ago) has no effect.  For some reason debugging gwt:devmode does not trigger my breakpoints, nor does adding console logging have any effect either in IDEA or in the browser.  Strange...

I do appreciate on gote's move being able to see the piece destinations for gote's pieces.

**Comment by Tellmarch** [comment] 2021-07-17 11:56
This should be fixed in the Snapshot version

**Closed by Tellmarch** 2021-07-17 11:56 UTC
